---

- name: activate NetworkBlockDevice
  modprobe:
    name: nbd
    state: present
    params: 'max_part=16'

- name: check existence of qcow2 image
  stat:
    path: "{{ hetzner_hypervisor_vms_path }}{{ vm.name }}.qcow2"
  register: qcow_exists

- block:
  - name: create qcow2 file if not exists
    command: "virsh vol-create-as {{ hetzner_hypervisor_default_storage_pool }} {{ vm.name }}.qcow2 {{ vm.size }} --prealloc-metadata --format qcow2"

  - name: create another tmpdir
    command: mktemp -d
    register: _mktemp

  - name: set target (tmpfs)
    set_fact:
      _bootstrap_target: "{{ _mktemp.stdout }}"

  - name: mount tmpfs
    command: "mount -t tmpfs -o size=2G none {{ _bootstrap_target }}"

  - name: debootstrap
    command: "eatmydata debootstrap {{ hetzner_hypervisor_guest_debian_version }} {{ _bootstrap_target }}"
    async: 86400
    poll: 15

  - name: bind mount pseudo filesystems
    shell: "mkdir -p {{ _bootstrap_target }}/{{ item }}; mount --bind /{{ item }} {{ _bootstrap_target }}/{{ item }}"
    register: _pseudomount
    with_items:
    - proc
    - sys
    - dev
    - dev/pts

  - name: update sources
    shell: "DEBIAN_FRONTEND=noninteractive chroot {{ _bootstrap_target }} apt-get update"

  - name: install eatmydata
    shell: "DEBIAN_FRONTEND=noninteractive chroot {{ _bootstrap_target }} apt-get -y install eatmydata"

  - name: install packages
    shell: "DEBIAN_FRONTEND=noninteractive chroot {{ _bootstrap_target }} eatmydata apt-get -y install less locales-all vim nano sudo resolvconf ssh linux-image-amd64 grub-pc python"
    async: 86400
    poll: 15

  - name: clean up packages
    command: "chroot {{ _bootstrap_target }} eatmydata apt-get clean"

  - name: umount pseudo filesystems
    command: umount {{ _bootstrap_target }}/{{ item }}
    with_items:
    - dev/pts
    - proc
    - sys
    - dev

  - name: connect the qcow device
    command: "qemu-nbd -c /dev/nbd0 {{ hetzner_hypervisor_vms_path }}{{ vm.name }}.qcow2"

  - name: Create BIOS Boot partition (for grub)
    command: sgdisk -n 1:0:+1M -t 1:ef02 /dev/nbd0

  - name: Create boot partition
    command: sgdisk -n 2:0:+1024M -t 2:8200 /dev/nbd0

  - name: Create root partition
    command: sgdisk -n 3:0:0 -t 3:8200 /dev/nbd0

  - name: format boot partition
    filesystem:
      fstype: ext4
      dev: /dev/nbd0p2

  - name: format root partition
    filesystem:
      fstype: ext4
      dev: /dev/nbd0p3

  - name: mount root partition
    command: mount /dev/nbd0p3 /mnt/

  - name: create /mnt/boot directory
    file:
      state: directory
      path: /mnt/boot

  - name: mount boot partition
    command: mount /dev/nbd0p2 /mnt/boot/

  - name: copy data from temp
    shell: cp -a {{ _bootstrap_target }}/* /mnt/

  - name: bind mount pseudo filesystems
    shell: mkdir -p /mnt/{{ item }}; mount --bind /{{ item }} /mnt/{{ item }}
    with_items:
    - proc
    - sys
    - dev
    - dev/pts

  - name: umount tmpfs
    command: "umount {{ _bootstrap_target }}"

  - name: remove tmpfs
    file:
      state: absent
      dest: "{{ _bootstrap_target }}"

  - name: get boot Device UUID
    command: blkid -o value /dev/nbd0p2
    register: _device_uuid

  - name: set boot UUID
    set_fact:
      boot_device_uuid: "{{ _device_uuid.stdout_lines[0] }}"

  - name: get root Device UUID
    command: blkid -o value /dev/nbd0p2
    register: _device_uuid

  - name: set root UUID
    set_fact:
      root_device_uuid: "{{ _device_uuid.stdout_lines[0] }}"

  - name: add fstab
    template:
      src: fstab.j2
      dest: /mnt/etc/fstab
      owner: root
      group: root
      mode: '0644'
      backup: yes

  - name: add interfaces
    template:
      src: guest_interfaces.j2
      dest: /mnt/etc/network/interfaces
      owner: root
      group: root
      mode: '0644'
      backup: yes

  - name: set hostname
    copy:
      content: "{{ vm.name }}"
      dest: /mnt/etc/hostname

  - name: create /root/.ssh directory
    file:
      state: directory
      path: /mnt/root/.ssh

  - name: copy root key
    copy:
      src: /root/.ssh/authorized_keys
      dest: /mnt/root/.ssh/authorized_keys
      owner: root
      group: root
      mode: 0600
      remote_src: True

  - name: copy .bash_aliases
    copy:
      src: bash_aliases
      dest: /mnt/root/.bash_aliases
      owner: root
      group: root
      mode: 0644

  - name: copy .bashrc
    copy:
      src: bashrc
      dest: /mnt/root/.bashrc
      owner: root
      group: root
      mode: 0644

  - name: copy .profile
    copy:
      src: profile
      dest: /mnt/root/.profile
      owner: root
      group: root
      mode: 0644

  - name: delete supplied keys
    file:
      state: absent
      dest: "/mnt/etc/ssh/ssh_host_{{ item.algo }}_key"
    with_items: "{{ hetzner_hypervisor_ssh_host_keys }}"

  - name: delete supplied pub keys
    file:
      state: absent
      dest: "/mnt/etc/ssh/ssh_host_{{ item.algo }}_key.pub"
    with_items: "{{ hetzner_hypervisor_ssh_host_keys }}"

  - name: generate (better) ssh host keys
    command: >
      chroot /mnt ssh-keygen -q -N '' -t {{ item.algo }} -b {{ item.keylen }}
      -f /etc/ssh/ssh_host_{{ item.algo }}_key
    with_items: "{{ hetzner_hypervisor_ssh_host_keys }}"

  - name: set up grub
    command: chroot /mnt update-grub

  - name: install boot loader (grub)
    command: chroot /mnt grub-install /dev/nbd0

  - name: replace /dev/nbd0p1 with /dev/vda1
    replace:
      dest: /mnt/boot/grub/grub.cfg
      regexp: 'nbd0p3'
      replace: 'vda3'

  - name: umount pseudo filesystems
    command: umount /mnt/{{ item }}
    with_items:
    - dev/pts
    - proc
    - sys
    - dev

  - name: unmount boot
    command: umount /dev/nbd0p2

  - name: unmount root
    command: umount /dev/nbd0p3

  - name: unconnect the qcow device
    command: "qemu-nbd -d /dev/nbd0"

  - name: creaete vm
    command: virt-install -n {{ vm.name }}
             --memory={{ vm.ram }}
             --vcpus={{ vm.cores }}
             --cpu host
             --os-type=linux
             --disk vol={{ hetzner_hypervisor_default_storage_pool }}/{{ vm.name }}.qcow2,device=disk,bus=virtio,cache=writeback,sparse=no
             --network bridge=br0,model=virtio,mac={{ vm.mac }}
             --import
             --noautoconsole
             --autostart
             --graphics vnc,keymap=de

  # Block condition
  when: qcow_exists.stat.exists == False
# Block end

...
