---

- name: set package list
  set_fact:
    _package_list: "[ 'qemu-kvm', 'bridge-utils', 'uml-utilities', 'debootstrap', 'eatmydata', 'libvirt-bin', 'virtinst']"

- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install packages from backports
  apt:
    name: "{{item}}"
    state: installed
    default_release: "{{ ansible_distribution_release }}-backports"
    dpkg_options: 'force-confnew,force-confdef'
  with_items: "{{ _package_list }}"
  when: hetzner_hypervisor_install_from_backports

- name: install packages
  apt:
    name: "{{item}}"
    state: installed
  with_items: "{{ _package_list }}"
  when: not hetzner_hypervisor_install_from_backports

- name: activate ipv4 forwarding
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^net.ipv4.ip_forward"
    line: "net.ipv4.ip_forward=1"
    state: present

- name: activate ipv4 redirects
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^net.ipv4.conf.eth0.send_redirects"
    line: "net.ipv4.conf.eth0.send_redirects=0"
    state: present

#- name: activate ipv6 forwarding
#  lineinfile:
#    dest: /etc/sysctl.conf
#    regexp: "^net.ipv6.conf.all.forwarding"
#    line: "net.ipv6.conf.all.forwarding=1"
#    state: present

- name: activate forwarding
  command: sysctl -p

- name: edit interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: restart networking

- name: flush handler
  meta: flush_handlers

- name: create storage pool
  include: createstoragepool.yml

- name: create vms
  include: createvm.yml
  with_items: "{{ hetzner_hypervisor_vms }}"
  loop_control:
    loop_var: vm

- name: add users to libvirt group
  user:
    name: '{{ item }}'
    groups: libvirt
    append: yes
  with_items: "{{ hetzner_hypervisor_libvirt_members }}"
  when: ansible_distribution == 'Debian'

- name: add users to libvirtd group
  user:
    name: '{{ item }}'
    groups: libvirtd
    append: yes
  with_items: "{{ hetzner_hypervisor_libvirt_members }}"
  when: ansible_distribution == 'Ubuntu'

...
