---

- name: fail hetzner_hypervisor when machine is not debian stretch or ubuntu xenial
  fail:
    msg: "host {{ansible_host}} is not of os type Debian Stretch or Ubuntu Xenial"
  when: not ((ansible_distribution == 'Debian' and ansible_distribution_release == 'stretch') or (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'xenial'))

- name: set package list debian
  set_fact:
    _package_list: "[ 'python-lxml', 'qemu-kvm', 'bridge-utils', 'uml-utilities', 'debootstrap', 'libvirt-daemon-system', 'libvirt-clients', 'eatmydata', 'virtinst']"
  when: ansible_distribution == 'Debian'

- name: set package list ubuntu
  set_fact:
    _package_list: "[ 'python-lxml', 'qemu-kvm', 'bridge-utils', 'uml-utilities', 'debootstrap', 'eatmydata', 'libvirt-bin', 'virtinst']"
  when: ansible_distribution == 'Ubuntu'

- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install packages
  apt:
    name: "{{item}}"
    state: installed
    dpkg_options: 'force-confnew,force-confdef'
  with_items: "{{ _package_list }}"

- name: activate ipv4 forwarding
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^net.ipv4.ip_forward"
    line: "net.ipv4.ip_forward=1"
    state: present
  notify: restart networking

- name: activate ipv4 redirects ubuntu
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "^net.ipv4.conf.{{ ansible_default_ipv4.interface }}.send_redirects"
    line: "net.ipv4.conf.{{ ansible_default_ipv4.interface }}.send_redirects=0"
    state: present
  notify: restart networking

#- name: activate ipv6 forwarding
#  lineinfile:
#    dest: /etc/sysctl.conf
#    regexp: "^net.ipv6.conf.all.forwarding"
#    line: "net.ipv6.conf.all.forwarding=1"
#    state: present

- name: activate forwarding
  command: sysctl -p

- name: edit interfaces
  template:
    src: interfaces.j2
    dest: /etc/network/interfaces
    owner: root
    group: root
    mode: '0644'
    backup: yes

- name: flush handler
  meta: flush_handlers

- name: create storage pool
  include: createstoragepool.yml

- name: activate NetworkBlockDevice
  modprobe:
    name: nbd
    state: present
    params: 'max_part=16'

- name: iterate vms
  include: vm.yml
  with_items: "{{ hetzner_hypervisor_vms }}"
  loop_control:
    loop_var: vm

- name: add users to libvirt group
  user:
    name: '{{ item }}'
    groups: libvirt
    append: yes
  with_items: "{{ hetzner_hypervisor_libvirt_members }}"
  when: ansible_distribution == 'Debian'

- name: add users to libvirtd group
  user:
    name: '{{ item }}'
    groups: libvirtd
    append: yes
  with_items: "{{ hetzner_hypervisor_libvirt_members }}"
  when: ansible_distribution == 'Ubuntu'

...
